name: histouric_mobile_frontend
description: A new Flutter project for the HisTouric App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.4.0
  flutter_animated_progress_bar: ^1.0.5
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.7
  go_router: ^10.1.0
  percent_indicator: ^4.2.3
  audioplayers: ^5.1.0
  flutter_polyline_points: ^2.0.0
  permission_handler: ^10.4.3
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
